# Generated by Django 3.1.1 on 2020-09-25 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0002_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('event_img', models.ImageField(upload_to='event_pics')),
                ('event_date', models.DateTimeField()),
                ('event_location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('slug', models.SlugField(blank=True)),
                ('open_slot', models.IntegerField(default=5, null=True)),
                ('attend', models.ManyToManyField(blank=True, default=None, related_name='attendees', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='Events.category', verbose_name='Categories')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
